menu:
  Documentation: https://saleor.readthedocs.io/en/latest/
  Github: https://github.com/mirumee/saleor
  Services: /#services
  Demo: http://demo.getsaleor.com
  Get started: https://mirumee.typeform.com/to/gf97sQ