menu:
  Docs: https://saleor.readthedocs.io/en/latest/
  Services: /#services
  Demo: http://demo.getsaleor.com

menuNewCart:
  Docs: true
  Services: false
  Demo: true

noFollow:
  Docs: true
  Services: false
  Demo: false
