menu:
  Docs: https://saleor.readthedocs.io/en/latest/
  Roadmap: /roadmap/
  Privacy Policy: /privacy/
  Services: /#services
  Blog: https://medium.com/saleor
  Demo: http://demo.getsaleor.com

menuNewCart:
  Docs: true
  Services: false
  Demo: true

noFollow:
  Docs: true
  Services: false
  Demo: false