menu:
  Documentation: https://saleor.readthedocs.io/en/latest/
  Services: /#services
  Demo: http://demo.getsaleor.com
  Get started: https://github.com/mirumee/saleor

menuNewCart:
  Documentation: true
  Services: false
  Demo: true
  Get started: true
  